name: Go
resident: true
category: compiler
compiler_image: combobox-go
runner_image: combobox-runner:1.0.1
default_script: build
versions:
  "1.21":
    image_tag: "1.21"
    cache_volumes:
      - volume_name: combobox-go-pkg-1.21
        mount_path: /go/pkg
      - volume_name: combobox-go-cache-1.21
        mount_path: /home/dummy/.cache/go-build
  "1.22":
    image_tag: "1.22"
    cache_volumes:
      - volume_name: combobox-go-pkg-1.22
        mount_path: /go/pkg
      - volume_name: combobox-go-cache-1.22
        mount_path: /home/dummy/.cache/go-build
  "1.23":
    image_tag: "1.23"
    cache_volumes:
      - volume_name: combobox-go-pkg-1.23
        mount_path: /go/pkg
      - volume_name: combobox-go-cache-1.23
        mount_path: /home/dummy/.cache/go-build
compiler_resources:
  ram: 300
  cpus: 1000
  cpu_time: 20000
  net: 50
  run_time: 20
  tmp_dir: 80
