name: Rust
category: compiler
compiler_image: combobox-rust
runner_image: combobox-runner:1.0.1
default_script: build
versions:
  "1.85":
    image_tag: "1.85"
    cache_volumes:
      - volume_name: combobox-rust-cargo-1.85
        mount_path: /home/dummy/.cargo
      - volume_name: combobox-rust-project-1.85
        mount_path: /home/dummy/project
compiler_resources:
  ram: 300
  cpus: 1000
  cpu_time: 20000
  net: 50
  run_time: 20
  tmp_dir: 80
